version: '3'

services:
  vega-web-backend:
    build:
      context: ./server
    image: "venus/quantum"
    networks:
      - vega-web-backend-net
      - vega-spring-backend-net
    ports:
      - "8000:8000"
  vega-web-frontend:
    build:
      context: ./
    image: "venus/theswitch"
    networks:
      - vega-web-backend-net
    ports:
      - "3000:3000"
networks:
  vega-web-backend-net:
    driver: bridge
    name: "vega-web-backend-net"
  vega-spring-backend-net:
    external: true
